# Pipeline schedule vars
# KI_BUILD_TYPE
#   daily
#   monthly
#   release

variables:
  CONTAINER_NAME: kicad
  GL_CONTAINER_ROOT: ${CI_REGISTRY}/${CI_PROJECT_PATH}
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - deploy

.template:build_base:
  tags:
    - kicad-dind
  image: docker:24.0.9
  services:
    - docker:24.0.9-dind
  stage: build
  variables:
    GL_CONTAINER: "${GL_CONTAINER_ROOT}/${CONTAINER_NAME}"
  before_script:
    - apk add --no-cache bash
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin


.template:build:
  extends: .template:build_base
  script:
    - docker build --pull -t kicad:build-temp -f ${DOCKERFILE_PATH} .
    - echo $KI_BUILD_TYPE
    - echo $CONTAINER_TAG
    - echo $GL_CONTAINER
    - /bin/bash ./tag-helper.sh -c kicad:build-temp -t $KI_BUILD_TYPE -b $CONTAINER_TAG -i $GL_CONTAINER -p
  artifacts:
    paths:
      - docker_tags.txt

.template:build_arch:
  extends: .template:build_base
  image: docker:24.0.9
  services:
    - docker:24.0.9-dind
  script:
    - docker context create builder
    - docker buildx create builder --use
    - docker buildx build --platform linux/$ARCH --pull --load --tag kicad:$ARCH-build-temp -f ${DOCKERFILE_PATH} .
    - echo $KI_BUILD_TYPE
    - echo $CONTAINER_TAG
    - echo $GL_CONTAINER
    - /bin/bash ./tag-helper.sh -c kicad:$ARCH-build-temp -a $ARCH -t $KI_BUILD_TYPE -b $CONTAINER_TAG -i $GL_CONTAINER -p
  artifacts:
    paths:
      - $ARCH-docker_tags.txt

.template:build_release:
  extends: .template:build_base
  script:
    - docker build --pull -t kicad:build-temp -f ${DOCKERFILE_PATH} --build-arg="KICAD_VERSION=${VERSION}" .
    - echo $KI_BUILD_TYPE
    - echo $CONTAINER_TAG
    - echo $GL_CONTAINER
    - /bin/bash ./tag-helper.sh -c kicad:build-temp -t $KI_BUILD_TYPE -b $CONTAINER_TAG -r $VERSION -i $GL_CONTAINER -p
  artifacts:
    paths:
      - docker_tags.txt

.template:deploy_to_dh:
  image: docker:stable
  tags:
    - kicad-dind
  services:
    - docker:dind
  stage: deploy
  before_script:
    - apk add --no-cache bash
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - echo "$DH_PASSWORD" | docker login -u "$DH_USER" docker.io --password-stdin
    - echo "$GH_TOKEN" | docker login -u "$GH_USER" ghcr.io --password-stdin
  script:
    - /bin/bash ./deploy-helper.sh -i index.docker.io/kicad/kicad
    - /bin/bash ./deploy-helper.sh -i ghcr.io/kicad/kicad

.template:deploy_multi:
  image: docker:stable
  tags:
    - kicad-dind
  services:
    - docker:dind
  stage: deploy
  before_script:
    - apk add --no-cache bash
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - echo "$DH_PASSWORD" | docker login -u "$DH_USER" docker.io --password-stdin
    - echo "$GH_TOKEN" | docker login -u "$GH_USER" ghcr.io --password-stdin
  script:
    - /bin/bash ./deploy-helper-multi.sh -i index.docker.io/kicad/kicad -a arm64 -a amd64 -p
    - /bin/bash ./deploy-helper-multi.sh -i ghcr.io/kicad/kicad -a arm64 -a amd64 -p

build_nightly_amd64:
  extends: .template:build_arch
  variables:
    DOCKERFILE_PATH: Dockerfile.nightly
    CONTAINER_TAG: nightly
    ARCH: amd64
  rules:
    - if: $KI_BUILD_TYPE == "daily"

build_nightly_arm64:
  extends: .template:build_arch
  variables:
    DOCKERFILE_PATH: Dockerfile.nightly
    CONTAINER_TAG: nightly
    ARCH: arm64
  rules:
    - if: $KI_BUILD_TYPE == "daily"

deploy_nightly:
  extends: .template:deploy_multi
  dependencies:
    - build_nightly_amd64
    - build_nightly_arm64
  variables:
    CONTAINER_TAG: nightly
  rules:
    - if: $KI_BUILD_TYPE == "daily"

build_nightly_monthly:
  extends: .template:build
  variables:
    DOCKERFILE_PATH: Dockerfile.nightly
    CONTAINER_TAG: nightly
  rules:
    - if: $KI_BUILD_TYPE == "monthly"

deploy_nightly_monthly:
  extends: .template:deploy_to_dh
  dependencies:
    - build_nightly_monthly
  variables:
    CONTAINER_TAG: nightly
  rules:
    - if: $KI_BUILD_TYPE == "monthly"

build_8:
  extends: .template:build_release
  variables:
    DOCKERFILE_PATH: Dockerfile.8.0-stable
    CONTAINER_TAG: "8.0"
  rules:
    - if: $KI_BUILD_TYPE == "release"

deploy_8:
  extends: .template:deploy_to_dh
  rules:
    - if: $KI_BUILD_TYPE == "release"
  dependencies:
    - build_8
  variables:
    CONTAINER_TAG: "8.0"