name: 'Clean old images'

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # every hour

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete untagged images (nightlies mainly)
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: KiCad
          token: ${{ secrets.RETENTION_PAT }}
          image-names: "kicad"
          tag-selection: untagged
          cut-off: 1w
          dry-run: false