name: 'Repo Lockdown'

on:
    pull_request_target:
      types: opened

permissions:
    pull-requests: write

jobs:
    action:
        runs-on: ubuntu-latest
        steps:
        - uses: dessant/repo-lockdown@v4
        with:
          pr-comment: >
            This repository does not accept pull requests.
            Merged requests must be submitted on GitLab 
            https://gitlab.com/kicad/packaging/kicad-cli-docker
          skip-closed-pr-comment: true